### ISSUE TITLE
Crashed while loading new game [.11]

### ISSUE THREAD

**Issue by RichardB122** [Morgan-Allen/Presidium-Graphics-Overhaul#3]
So I downloaded release .11 and I tried to play, I setup the game and clicked begin, but when it got to the loading screen it just stopped loading about halfway through. I went to check the log file and it said this:

REGISTERING NEW BASE: ArtilectsException in thread "Thread-3" java.lang.NullPointerException
	at stratos.game.wild.NestUtils.populateFauna(NestUtils.java:119)
	at stratos.game.verse.SectorScenario.establishLocals(SectorScenario.java:289)
	at stratos.game.verse.SectorScenario.configureScenario(SectorScenario.java:179)
	at stratos.content.hooks.ScenarioTerra.configureScenario(ScenarioTerra.java:88)
	at stratos.start.Scenario$1.run(Scenario.java:162)

**Comment by Morgan-Allen** [comment]
Hi there Richard- first of all, thanks very much for the report!  I'll investigate this as soon as possible and get back to you.

**Comment by Morgan-Allen** [comment]
Hi there Richard- I think that bug is specific to the quest in that sector (it was basically looking for a nest definition for artilects, who actually spawn from ruins.)  I discovered a different bug which affects sprite offsets, so you might see some visual glitches until I can nail that down.

Anyway, I updated the builds for both OSX and Windows, so you should be able to play now.  Let me know if you hit any other problems.

(PS- out of interest, what's the OS and version number for your machine?)

**Comment by Morgan-Allen** [comment]
Anyway, if you can just verify the newer build works, I'll close up.

**Comment by RichardB122** [comment]
I tried it out and it seems to be fixed. Thanks! I am running Windows 7 SP1 and Java 7.

**Comment by Morgan-Allen** [comment]
Cool.  Done.
